contracts: Add ETH support
hop-exchange/contracts pull request #23
Opened 2021-02-27 20:29 UTC by cwhinfrey

Allows the `L1_Bridge` and `L2_Bridge` to support ETH directly.

The `L1_Bridge` implements this using inheritance. Either `L1_ETH_Bridge` or `L1_ERC20_Bridge` should be deployed.

The `L2_Bridge` uses a flag `l2CanonicalTokenIsWeth`. If set true, the bridge will wrap incoming ETH in WETH and unwrap outgoing WETH to distribute as ETH.

The reason for handling it in two different ways involves a few reasons but it's mostly because we already use inheritance to implement the L2 bridge for arbitrum, optimism, ect. Adding another split in the tree for eth/erc20 would mean we need two `L2_Bridge` contracts for each network and a complicated inheritance structure to keep the code DRY.

@shanefontaine All broken tests should be fixed by using `L1_ERC20_Bridge` instead of `L1_Bridge` and passing in `false` to the L2_Bridge constructor for `l2CanonicalTokenIsWeth`. I didn't make these changes to avoid merge conflicts.

2021-02-28 07:53 UTC, shanefontaine requested changes

2021-02-28 07:53 UTC, shanefontaine commented on contracts/bridges/L1_ETH_Bridge.sol
> +        governance = msg.sender;
Does it make sense to instantiate this up a level for DRYness?

2021-02-28 07:53 UTC, shanefontaine commented on contracts/bridges/L1_ETH_Bridge.sol
> +        require(success, 'TransferHelper::safeTransferETH: ETH transfer failed');
I think it would make sense to be consistent with our error messages here as well (`L1_ERC2_BRG: ...`).

Not a super strong opinion here.

2021-02-28 08:05 UTC, shanefontaine commented
The code looks good. I think this may introduce a lot of conditional complexity to the off-chain code. If I am thinking about it correctly, we will probably have to make some off-chain utils to wrap all the ERC20 functionality and return a correct value if we are dealing with ETH.

I am probably missing something, but do you think it would make sense to convert to/from WETH only on `stake()` and `unstake()`? If we handle the conversion there, all other functions only need to be concerned about ERC20. I believe one downside there is that there may not be an ETH/WETH conversion available on a given L2.

Some random, related thoughts:
* It might make sense to just add a contract between the Bonder and the Bridge that accepts ETH and converts to WETH (and subsequently sends to the Bridge). Separate concerns and keep the contracts simple.
* The last point would not work in the case where an L2 uses a generic ERC20 contract for WETH instead of the actual WETH contract. If this is the case, I think that specific L2 would have broader issues.

2021-03-02 01:53 UTC, cwhinfrey commented
Back to you @shanefontaine

2021-03-02 01:56 UTC, shanefontaine approved these changes
👍

2021-03-02 01:56 UTC, merged