Feature/internal audit 4
hop-exchange/contracts pull request #28
Opened 2021-03-03 08:08 UTC by cwhinfrey

* Add ability to pause sends to chainIds
  * Allows supported chains to be shut down
* Require TransferRoot is bonded after it is committed
  * Keeps Bonders from tricking challengers into challenging a future TransferRoot
* Only distribute relayerFee when bonding
  * Keeps outside accounts from calling withdraw and claiming relayerFee
* relayerFee -> bonderFee
  * Name change
* Add a minimum bonder fee
  * Mitigate griefing attacks from both very large sends and many small sends
* Add relayer fee for L1 -> L2 payments
  * Allows a relayer to collect a fee and recoup any L2 gas costs

2021-03-03 16:11 UTC, shanefontaine requested changes

2021-03-03 16:11 UTC, shanefontaine commented on contracts/bridges/L2_Bridge.sol
> +    function setMinimumBonderFeeRequirements(uint256 _minBonderBps, uint256 _minBonderFeeAmount) external onlyGovernance {
Potential name change if naming convention is changed in comment above

2021-03-03 16:11 UTC, shanefontaine commented on contracts/bridges/L1_Bridge.sol
> +        require(isChainIdPaused[chainId] == false, "L1_BRG: Sends to this chainId are paused");
Discussion point: it might make sense to make these two modifiers. No strong opinion here.

2021-03-03 16:11 UTC, shanefontaine commented on contracts/bridges/L1_Bridge.sol
> +    function setChainIdDepositsPaused(uint256 chainId, bool paused) external onlyGovernance {
Nitpick: `paused` -> `isPaused`

2021-03-03 16:11 UTC, shanefontaine commented on contracts/bridges/L2_Bridge.sol
>      /// @notice amount is the amount the user wants to send plus the relayer fee
"Relayer fee" in notice

2021-03-03 16:11 UTC, shanefontaine commented on contracts/bridges/L2_Bridge.sol
>          uint256 chainId,
"Relayer fee" in notice (Comment is attached to this line arbitrarily because GitHub doesn't let you comment on unchanged code.)

2021-03-03 17:57 UTC, cwhinfrey commented on contracts/bridges/L1_Bridge.sol
> +                _addCredit(transferBond.bonder, getBondForTransferAmount(transferRoot.total));
👍 Comment updated

2021-03-03 22:19 UTC, cwhinfrey commented on contracts/bridges/L2_Bridge.sol
> +    uint256 public minBonderFeeAmount = 6 * 1e13;
Going to default this to 0 and then it can be raised through the setter if dust transactions become an issue.

2021-03-03 22:24 UTC, cwhinfrey commented on contracts/bridges/L2_Bridge.sol
> +        minBonderFee = minBonderFee > minBonderFeeAmount ? minBonderFee : minBonderFeeAmount;
Updated to `minBonderFeeAbsolute` `minBonderFeeRelative`. Thinking introducing `max` is overkill but let me know what you think.

2021-03-03 22:28 UTC, cwhinfrey commented on contracts/bridges/L1_Bridge.sol
> +        require(isChainIdPaused[chainId] == false, "L1_BRG: Sends to this chainId are paused");
No strong opinion either but leaning slightly towards leaving as is.

2021-03-04 00:08 UTC, cwhinfrey commented
@shanefontaine back to you

2021-03-04 00:46 UTC, shanefontaine approved these changes
👍

2021-03-04 00:46 UTC, merged