contracts: Add force commit
hop-exchange/contracts pull request #6
Opened 2021-02-09 06:29 UTC by cwhinfrey

2021-02-09 13:52 UTC, shanefontaine requested changes

2021-02-09 13:52 UTC, shanefontaine commented on contracts/bridges/L2_Bridge.sol
>      function commitTransfers(uint256 _destinationChainId) public onlyBonder {
@cwhinfrey I believe the `onlyBonder` modifier should be removed now that the check is inline

2021-02-09 21:31 UTC, shanefontaine requested changes

2021-02-09 21:31 UTC, shanefontaine commented on contracts/bridges/L2_Bridge.sol
> +        uint minForceCommitTime = lastCommitTimeForChainId[_destinationChainId].add(minimumForceCommitDelay);
@cwhinfrey Thoughts on making this `uint256` for consistency?

2021-02-10 00:20 UTC, cwhinfrey commented on contracts/bridges/L2_Bridge.sol
>      function commitTransfers(uint256 _destinationChainId) public onlyBonder {
Ended up making a separate internal function because we only need this check when `commitTransfers` is called directly.

2021-02-10 00:23 UTC, cwhinfrey commented
Back at you @shanefontaine 

I changed the TransferRoots to be indexed by the "Transfer Root Id" which is a hash of the `root` and `totalAmount`. This fixes some issues where the Bonder bonds a valid TransferRoot with a very low amount as a griefing attack.

2021-02-10 00:24 UTC, cwhinfrey commented
If this looks good, I'm going to do a pass to clean up the naming. It's pretty inconsistent right now.

2021-02-10 01:29 UTC, shanefontaine approved these changes
👍

2021-02-10 01:29 UTC, merged